# Generated by Django 4.0.3 on 2022-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=50000)),
                ('photo', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
