# Generated by Django 4.0.3 on 2022-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='diary',
            name='photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
