# Generated by Django 4.0.3 on 2022-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_diary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
